<?php

use App\Countries;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement("SET foreign_key_checks=0");
        
        Countries::truncate();
        $current_datetime=now();
        // $data=array(
        //     array('country_country_name'=>'Afghanistan','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
        //     array('country_country_name'=>'Albania','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
        //     array('country_country_name'=>'Algeria','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
        //     array('country_country_name'=>'Andorra','created_at'=>$current_datetime,'updated_at'=>$current_datetime)
        //     ); 
            $data = array(
                array('country_name' => 'United States','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Canada','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Afghanistan','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Albania','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Algeria','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'American Samoa','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Andorra','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Angola','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Anguilla','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Antarctica','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Antigua and/or Barbuda','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Argentina','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Armenia','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Aruba','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Australia','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Austria','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Azerbaijan','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Bahamas','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Bahrain','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Bangladesh','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Barbados','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Belarus','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Belgium','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Belize','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Benin','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Bermuda','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Bhutan','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Bolivia','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Bosnia and Herzegovina','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Botswana','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Bouvet Island','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Brazil','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'British lndian Ocean Territory','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Brunei Darussalam','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Bulgaria','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Burkina Faso','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Burundi','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Cambodia','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Cameroon','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Cape Verde','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Cayman Islands','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Central African Republic','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Chad','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Chile','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'China','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Christmas Island','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Cocos (Keeling) Islands','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Colombia','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Comoros','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Congo','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Cook Islands','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Costa Rica','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Croatia (Hrvatska)','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Cuba','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Cyprus','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Czech Republic','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Democratic Republic of Congo','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Denmark','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Djibouti','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Dominica','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Dominican Republic','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'East Timor','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Ecudaor','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Egypt','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'El Salvador','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Equatorial Guinea','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Eritrea','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Estonia','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Ethiopia','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Falkland Islands (Malvinas)','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Faroe Islands','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Fiji','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Finland','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'France','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'France, Metropolitan','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'French Guiana','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'French Polynesia','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'French Southern Territories','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Gabon','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Gambia','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Georgia','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Germany','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Ghana','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Gibraltar','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Greece','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Greenland','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Grenada','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Guadeloupe','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Guam','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Guatemala','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Guinea','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Guinea-Bissau','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Guyana','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Haiti','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Heard and Mc Donald Islands','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Honduras','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Hong Kong','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Hungary','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Iceland','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'India','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Indonesia','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Iran (Islamic Republic of)','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Iraq','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Ireland','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Israel','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Italy','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Ivory Coast','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Jamaica','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Japan','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Jordan','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Kazakhstan','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Kenya','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Kiribati','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Korea, Democratic People\'s Republic of','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Korea, Republic of','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Kuwait','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Kyrgyzstan','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Lao People\'s Democratic Republic','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Latvia','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Lebanon','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Lesotho','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Liberia','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Libyan Arab Jamahiriya','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Liechtenstein','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Lithuania','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Luxembourg','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Macau','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Macedonia','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Madagascar','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Malawi','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Malaysia','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Maldives','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Mali','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Malta','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Marshall Islands','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Martinique','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Mauritania','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Mauritius','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Mayotte','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Mexico','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Micronesia, Federated States of','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Moldova, Republic of','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Monaco','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Mongolia','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Montserrat','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Morocco','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Mozambique','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Myanmar','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Namibia','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Nauru','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Nepal','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Netherlands','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Netherlands Antilles','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'New Caledonia','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'New Zealand','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Nicaragua','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Niger','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Nigeria','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Niue','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Norfork Island','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Northern Mariana Islands','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Norway','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Oman','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Pakistan','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Palau','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Panama','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Papua New Guinea','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Paraguay','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Peru','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Philippines','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Pitcairn','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Poland','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Portugal','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Puerto Rico','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Qatar','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Republic of South Sudan','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Reunion','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Romania','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Russian Federation','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Rwanda','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Saint Kitts and Nevis','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Saint Lucia','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Saint Vincent and the Grenadines','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Samoa','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'San Marino','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Sao Tome and Principe','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Saudi Arabia','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Senegal','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Serbia','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Seychelles','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Sierra Leone','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Singapore','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Slovakia','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Slovenia','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Solomon Islands','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Somalia','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'South Africa','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'South Georgia South Sandwich Islands','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Spain','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Sri Lanka','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'St. Helena','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'St. Pierre and Miquelon','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Sudan','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Suricountry_name','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Svalbarn and Jan Mayen Islands','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Swaziland','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Sweden','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Switzerland','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Syrian Arab Republic','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Taiwan','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Tajikistan','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Tanzania, United Republic of','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array( 'country_name' => 'Thailand','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Togo','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Tokelau','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Tonga','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Trinidad and Tobago','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Tunisia','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Turkey','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Turkmenistan','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Turks and Caicos Islands','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Tuvalu','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Uganda','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Ukraine','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'United Arab Emirates','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'United Kingdom','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'United States minor outlying islands','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Uruguay','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Uzbekistan','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Vanuatu','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Vatican City State','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Venezuela','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Vietnam','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Virgin Islands (British)','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Virgin Islands (U.S.)','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Wallis and Futuna Islands','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Western Sahara','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Yemen','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Yugoslavia','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Zaire','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Zambia','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
                array('country_name' => 'Zimbabwe','created_at'=>$current_datetime,'updated_at'=>$current_datetime),
            ); 
        DB::table('countries')->insert($data);
        DB::statement("SET foreign_key_checks=1");
    }
}
