name: Laravel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:
    runs-on: self-hosted
    steps:
    - name: change path
      run: cd /githubaction/sample-laravel-test/ && mkdir test
    - name: Install Dependencies
      run: mkdir jai
