name: Laravel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    - id: latest
      uses: thebritican/fetch-latest-release@v1.0.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: change path
      run: mkdir final

