name: Laravel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:
    runs-on: self-hosted
    steps:
    - name: change path
      run: |
        cd /githubaction/sample-laravel-test/
        mkdir final
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: anothrNick/github-tag-action@1.26.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
