name: Laravel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:
    runs-on: self-hosted
    steps:
    - name: change path
      run: |
        cd /githubaction/sample-laravel-test/
        mkdir final
  build:
    runs-on: ubuntu-latest
    - name: Bump version and push tag
      if: ${{ github.event_name == 'push' }}
      uses: anothrNick/github-tag-action@1.26.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
    - name: Rollback Release
      if: failure() && steps.create_release.outputs.id != ''
      uses: author/action-rollback@stable
      with:
        # Using a tag name
        tag: ${{ github.event_name }}
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
