name: Laravel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:
    runs-on: self-hosted
    steps:
    - name: change path
      run: |
        cd /githubaction/sample-laravel-test/
        mkdir final
    - name: Rollback Release
      if: failure()
      uses: author/action-rollback@stable
      with:
        # Using a known release ID
        release_id: ${{ steps.create_release.id }}
        # Using a tag name
        tag: 'v1.0.0'
     env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
